include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  BUNDLE: 'nibbles-git.flatpak'

flatpak:
  extends: '.flatpak'
  variables:
    MANIFEST_PATH: 'org.gnome.Nibbles.json'
    RUNTIME_REPO: 'https://sdk.gnome.org/gnome-nightly.flatpakrepo'
    FLATPAK_MODULE: 'gnome-nibbles'
    MESON_ARGS: ''
    APP_ID: 'org.gnome.Nibbles'

review:
  dependencies:
    - 'flatpak'
  extends: '.review'

stop_review:
  extends: '.stop_review'
